### ISSUE TITLE
It won't skip the items

### ISSUE THREAD

**Issue by Lapito** [3xz/auto-steam-queue#4]
I tried to use it, but the only thing that it does is skip the age verification.

**Comment by calebleung** [comment]
Hi, I actually disabled this functionality in the most recent update. You can automatically go through queues without having to load pages by using the UI on the [/explore](http://store.steampowered.com/explore/) (as seen in README doc). I'll consider adding a toggle for this feature in the future. 

If you want to restore this immediately, you can remove the multi-line comment on lines 167 and 172.

**Comment by Lapito** [comment]
Oh I see it now. Thanks!
