### ISSUE TITLE
Wrong path variable

### ISSUE THREAD

**Issue by MikFI** [3xz/auto-steam-queue#6]
In 4.0.1 update "var path = window.location.pathname.split('/')[1];" was changed to "var path = window.location.pathname.split('/').pop();"

By default "recommended list" opens with slash at the end ("http://store.steampowered.com/explore/"), where "explore" is the second element of array, not the last (which is "") - this make script unworkable

**Comment by calebleung** [comment]
Oops. We were trying to [work-around a Valve issue](https://github.com/3xz/auto-steam-queue/pull/3) when that was pulled in. Looking at the sticker page now, they seemed to have fixed the double slashes on their end, so I've just reverted it. Fingers crossed.

**Comment by 6apcyk** [comment]
Oh, I see. It still adds extra slash though. Maybe work with substrings then?
Something like: window.location.pathname.match(/\/(explore)(?:\/|$)/).pop()

**Comment by MikFI** [comment]
Oh, I see. Still adds extra slash from there, though. Tried to fix.
